//! `archive_spec` helpers extracted from `lib.rs` (pure code movement).
//! Re-exported from the crate root so the public API is unchanged.

pub(crate) struct ExportTableSpec {
    pub(crate) name: &'static str,
    pub(crate) columns: &'static [&'static str],
    pub(crate) order_by: &'static str,
}

pub(crate) const EXPORT_TABLES: &[ExportTableSpec] = &[
    ExportTableSpec {
        name: "schema_migrations",
        columns: &["version", "name", "applied_at", "checksum_sha256"],
        order_by: "version",
    },
    ExportTableSpec {
        name: "config_kv",
        columns: &["key", "value", "updated_at"],
        order_by: "key",
    },
    ExportTableSpec {
        name: "spaces",
        columns: &[
            "name",
            "display_name",
            "description",
            "default_silo",
            "ontology",
            "config_json",
            "created_at",
            "updated_at",
        ],
        order_by: "name",
    },
    ExportTableSpec {
        name: "silos",
        columns: &[
            "space_name",
            "name",
            "description",
            "retention_policy",
            "default_scope",
            "config_json",
            "created_at",
            "updated_at",
        ],
        order_by: "space_name, name",
    },
    ExportTableSpec {
        name: "source_episodes",
        columns: &[
            "id",
            "space_name",
            "source_type",
            "source_uri",
            "source_path",
            "source_description",
            "content",
            "content_sha256",
            "chunk_index",
            "chunk_count",
            "authority",
            "work_id",
            "chapter_id",
            "artifact_id",
            "git_commit",
            "tool_version",
            "metadata_json",
            "ingest_status",
            "ingested_at",
            "created_at",
            "updated_at",
        ],
        order_by: "id",
    },
    ExportTableSpec {
        name: "memories",
        columns: &[
            "id",
            "space_name",
            "silo_name",
            "scope",
            "project_key",
            "kind",
            "entity_key",
            "claim_key",
            "status",
            "active_version_id",
            "confidence",
            "pinned",
            "source_episode_id",
            "valid_from",
            "valid_to",
            "observed_at",
            "created_at",
            "updated_at",
            "accessed_at",
            "expires_at",
            "deleted_at",
            "metadata_json",
        ],
        order_by: "id",
    },
    ExportTableSpec {
        name: "memory_versions",
        columns: &[
            "id",
            "memory_id",
            "version_num",
            "content",
            "summary",
            "content_sha256",
            "source_episode_id",
            "source_ref_json",
            "created_at",
            "created_by",
            "event_id",
        ],
        order_by: "memory_id, version_num, id",
    },
    ExportTableSpec {
        name: "memory_events",
        columns: &[
            "id",
            "memory_id",
            "event_type",
            "old_status",
            "new_status",
            "actor",
            "reason",
            "data_json",
            "created_at",
        ],
        order_by: "created_at, id",
    },
    ExportTableSpec {
        name: "memory_tags",
        columns: &["memory_id", "tag", "created_at"],
        order_by: "memory_id, tag",
    },
    ExportTableSpec {
        name: "memory_links",
        columns: &[
            "src_memory_id",
            "dst_memory_id",
            "link_type",
            "status",
            "confidence",
            "event_id",
            "metadata_json",
            "created_at",
        ],
        order_by: "src_memory_id, dst_memory_id, link_type",
    },
    ExportTableSpec {
        name: "conflicts",
        columns: &[
            "id",
            "space_name",
            "status",
            "memory_a_id",
            "memory_b_id",
            "conflict_type",
            "explanation",
            "resolution",
            "resolution_event_id",
            "created_at",
            "updated_at",
            "resolved_at",
        ],
        order_by: "id",
    },
    ExportTableSpec {
        name: "entities",
        columns: &[
            "id",
            "space_name",
            "entity_key",
            "entity_type",
            "canonical_name",
            "status",
            "confidence",
            "source_episode_id",
            "metadata_json",
            "created_at",
            "updated_at",
        ],
        order_by: "id",
    },
    ExportTableSpec {
        name: "entity_aliases",
        columns: &[
            "entity_id",
            "alias",
            "normalized_alias",
            "source_episode_id",
            "created_at",
        ],
        order_by: "entity_id, normalized_alias",
    },
    ExportTableSpec {
        name: "relationships",
        columns: &[
            "id",
            "space_name",
            "subject_entity_id",
            "relation_type",
            "object_entity_id",
            "memory_id",
            "source_episode_id",
            "status",
            "confidence",
            "observed_at",
            "valid_from",
            "valid_to",
            "metadata_json",
            "created_at",
            "updated_at",
        ],
        order_by: "id",
    },
    ExportTableSpec {
        name: "processing_jobs",
        columns: &[
            "id",
            "kind",
            "target_type",
            "target_id",
            "status",
            "priority",
            "attempts",
            "max_attempts",
            "run_after",
            "locked_at",
            "locked_by",
            "input_json",
            "output_json",
            "error",
            "created_at",
            "updated_at",
        ],
        order_by: "id",
    },
    ExportTableSpec {
        name: "embeddings",
        columns: &[
            "id",
            "memory_id",
            "version_id",
            "source_episode_id",
            "embedding_model",
            "dimensions",
            "vector_blob",
            "status",
            "error",
            "created_at",
            "updated_at",
        ],
        order_by: "id",
    },
    ExportTableSpec {
        name: "dream_runs",
        columns: &[
            "id",
            "space_name",
            "status",
            "started_at",
            "finished_at",
            "budget_json",
            "summary_json",
            "error",
        ],
        order_by: "id",
    },
    ExportTableSpec {
        name: "probe_runs",
        columns: &[
            "id",
            "space_name",
            "probe_pack_name",
            "status",
            "started_at",
            "finished_at",
            "result_json",
        ],
        order_by: "id",
    },
];
